# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 03:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_Name', models.CharField(max_length=200)),
                ('Professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_First_Name', models.CharField(max_length=200)),
                ('Student_Last_Name', models.CharField(max_length=200)),
                ('Student_ID_Number', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='Student_List',
            field=models.ManyToManyField(to='prof.Student'),
        ),
    ]
