# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='Absent_Students',
            field=models.ManyToManyField(to='prof.Student'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='Present_Students',
            field=models.ManyToManyField(related_name='a', to='prof.Student'),
        ),
    ]
