# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0003_auto_20170117_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='Student_List',
            field=models.ManyToManyField(related_name='class_list', to='prof.Student'),
        ),
    ]
