# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0005_student_student_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'verbose_name': 'Attendance Record'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='Associated_Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Attendance_Records', to='prof.Class'),
        ),
    ]
