# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0007_auto_20170118_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='Associated_Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.Class'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='Present_Students',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='Associated_Class', chained_model_field='Student_Class', to='prof.Student'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='Student_Class',
        ),
        migrations.AddField(
            model_name='student',
            name='Student_Class',
            field=models.ManyToManyField(blank=True, null=True, to='prof.Class'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set([('Associated_Class', 'Date')]),
        ),
    ]
