# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0008_auto_20170119_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_Class',
            field=models.ManyToManyField(blank=True, to='prof.Class'),
        ),
    ]
