# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0010_student_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_ID_Number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
