# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0011_auto_20170119_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Student_Class',
        ),
    ]
